"""making password optional

Revision ID: b28496ff97ae
Revises: 68808f36849f
Create Date: 2026-08-11 10:52:09.080538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28496ff97ae'
down_revision: Union[str, Sequence[str], None] = '68808f36849f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socials_sid'), table_name='socials')
    op.drop_index(op.f('ix_socials_username'), table_name='socials')
    op.drop_table('socials')
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.create_index(op.f('ix_users_fullname'), 'users', ['fullname'], unique=False)
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_fullname'), table_name='users')
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'fullname')
    op.create_table('socials',
    sa.Column('sid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('followers', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('likes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('messaging_guaranteed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'RESERVED', 'SOLD', name='accountstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uid'], name=op.f('socials_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', name=op.f('socials_pkey'))
    )
    op.create_index(op.f('ix_socials_username'), 'socials', ['username'], unique=False)
    op.create_index(op.f('ix_socials_sid'), 'socials', ['sid'], unique=True)
    # ### end Alembic commands ###
